# This is a basic workflow to help you get started with Actions

name: Update DB

# Controls when the action will run. 
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job1:
    name: Modifiy repository files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.2

# If you execute some shell scripts or command lines to modify
# the files, use the 'run' key.
# More details, see "https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepsrun"

 
# If you execute an action to modify the files, use the 'uses' key.
# Just like as the previous step that executes the checkout action.
# More details, see "https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepsuses"
      - name: Setup Python
        uses: actions/setup-python@v2.2.1
          # The target architecture (x86, x64) of the Python interpreter.
      - name: Run script
        run: python main.py
          # Used to pull python distributions from actions/python-versions. Since there's a default, this is typically not supplied by the user.
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Commit and push changes
        run: |
          git config --global user.name "EliyaFishman"
          git config --global user.email "45822259+EliyaFishman@users.noreply.github.com"

          git add -A
          git commit -m "${{ steps.date.outputs.date }}"
          git push
